language: ruby
cache: bundler
rvm:
  - 2.1.2
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cups cups-pdf cups-bsd libcups2-dev
  - sudo apt-get install -qq -y imagemagick libmagickwand-dev nodejs
  - sudo apt-get install -qq -y xvfb gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable x11-apps
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - 'cp config/secrets.example.yml config/secrets.yml'
  - 'psql -c "create database print_hub_test;" -U postgres'
  - 'bundle exec rake db:migrate'
  - 'Xvfb -ac :99 -screen 0 1280x1024x16 &'
  - 'export DISPLAY=:99.0'
